# Generated by Django 6.0.4 on 2026-05-17 06:19

import casi.users.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[casi.users.api.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[casi.users.api.validators.validate_first_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[casi.users.api.validators.validate_last_name]),
        ),
    ]
