# Generated by Django 6.0.4 on 2026-05-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_verification_method_user_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
