# Generated by Django 6.0.4 on 2026-05-17 06:03

import casi.reviews.api.validators
import casi.reviews.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(validators=[casi.reviews.validators.validate_comment])),
                ('recommendation', models.CharField(choices=[('accept', 'ACCEPT'), ('reject', 'REJECT'), ('major_revision', 'MAJOR REVISION'), ('minor_revision', 'Minor Revision')], max_length=20)),
                ('is_submitted', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='reviews/file', validators=[casi.reviews.validators.validate_file])),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submission.submission')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('submission', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ReviewAssigment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(validators=[casi.reviews.api.validators.validate_time_zone])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('asigment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reviews.review')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='submission.submission')),
            ],
            options={
                'verbose_name': 'Reviewer Assignment',
                'verbose_name_plural': 'Reviewer Assignments',
                'ordering': ['-created_at'],
                'unique_together': {('submission', 'reviewer')},
            },
        ),
    ]
