# Generated by Django 6.0.4 on 2026-05-12 17:18

import casi.reviews.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0002_submission_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(validators=[casi.reviews.validators.validate_comment])),
                ('recommendation', models.CharField(choices=[('accept', 'ACCEPT'), ('reject', 'REJECT'), ('major_revision', 'MAJOR REVISION'), ('minor_revision', 'Minor Revision')], max_length=20)),
                ('is_submitted', models.BooleanField(default=False)),
                ('round', models.PositiveIntegerField(default=1)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submission.submission')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
