# Generated by Django 6.0.4 on 2026-05-12 17:39

import casi.reviews.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('submission', '0002_submission_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reviews/file', validators=[casi.reviews.validators.validate_file]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('submission', 'reviewer', 'round')},
        ),
    ]
