# Generated by Django 6.0.4 on 2026-05-13 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_file_alter_review_unique_together'),
        ('submission', '0002_submission_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('submission', 'reviewer')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='round',
        ),
    ]
