# Generated by Django 6.0.4 on 2026-05-17 06:03

import casi.submission.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, validators=[casi.submission.validators.validate_title])),
                ('abstract', models.TextField(validators=[casi.submission.validators.validate_abstract])),
                ('file', models.FileField(upload_to='submission/file', validators=[casi.submission.validators.validate_file])),
                ('keyword', models.JSONField(default=list, validators=[casi.submission.validators.validate_keyword])),
                ('cover_letter', models.TextField(blank=True, null=True, validators=[casi.submission.validators.validate_cover_letter])),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ManyToManyField(blank=True, null=True, to='authors.author')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journal')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journals.volume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
