# Generated by Django 6.0.4 on 2026-05-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
