# Generated by Django 6.0.4 on 2026-05-09 21:40

import casi.journals.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, validators=[casi.journals.validators.validate_name])),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal/image', validators=[casi.journals.validators.validate_image_or_logo])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='journal/logo', validators=[casi.journals.validators.validate_image_or_logo])),
                ('issn', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[casi.journals.validators.validate_issn])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalRequirements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField(default=dict)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='journals.journal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('issue', models.CharField(max_length=20, validators=[casi.journals.validators.validate_issue])),
                ('year', models.PositiveIntegerField()),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='journals.journal')),
            ],
            options={
                'ordering': ['-year', '-number'],
                'unique_together': {('journal', 'number', 'issue', 'year')},
            },
        ),
    ]
