# Generated by Django 6.0.4 on 2026-05-11 13:57

import casi.journals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalrequirements',
            name='content',
            field=models.JSONField(default=dict, validators=[casi.journals.validators.validate_requirements_content]),
        ),
    ]
