# Generated by Django 6.0.4 on 2026-05-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='number',
            field=models.IntegerField(),
        ),
    ]
