# Generated by Django 6.0.4 on 2026-05-09 21:40

import casi.authors.validators.validators
import django.contrib.postgres.indexes
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200, validators=[casi.authors.validators.validators.valideate_firstname])),
                ('last_name', models.CharField(max_length=200, validators=[casi.authors.validators.validators.valideate_lastname])),
                ('affiliation', models.CharField(max_length=200, validators=[casi.authors.validators.validators.validate_affilation])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('orc_id', models.CharField(blank=True, max_length=19, null=True, unique=True, validators=[casi.authors.validators.validators.validate_orcid])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['last_name', 'first_name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['first_name', 'last_name'], name='author_full_name_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops'])],
            },
        ),
    ]
